title: Endless Transit | Neural Link Manual
description: An infinite procedural universe simulation and text-adventure.
baseurl: "/endless-transit" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

markdown: kramdown
theme: minima # We will override this with our custom layout
exclude:
  - arch
  - archive
  - vision
  - workflow
